services:
  gateway:
    build:
      context: .
      dockerfile: ./cmd/gateway/Dockerfile
    container_name: mini_gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - user-service
      - todo-service

  user-service:
    build:
      context: .
      dockerfile: ./cmd/user-service/Dockerfile
    container_name: mini_user_service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  todo-service:
    build:
      context: .
      dockerfile: ./cmd/todo-service/Dockerfile
    container_name: mini_todo_service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
