services:
  postgres:
    image: postgres:15-alpine
    container_name: mini_maestro_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_mircoservice
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d demo_mircoservice"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: ./cmd/gateway/Dockerfile
    container_name: mini_gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - user-service
      - todo-service

  user-service:
    build:
      context: .
      dockerfile: ./cmd/user-service/Dockerfile
    container_name: mini_user_service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=demo_mircoservice
    depends_on:
      postgres:
        condition: service_healthy

  todo-service:
    build:
      context: .
      dockerfile: ./cmd/todo-service/Dockerfile
    container_name: mini_todo_service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082

volumes:
  postgres_data:
